modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
issueTrackerURL="${mod_issues_url}"
license="LGPL v2.1"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.justenoughbuttons]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.justenoughbuttons]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_loader_version},)"
    ordering="NONE"
    side="BOTH"